from django.core.management.base import BaseCommand
from apps.catalog.models import Category, Product


CATEGORIES_DATA = [
    {'name': 'Outerwear', 'slug': 'outerwear'},
    {'name': 'Knitwear', 'slug': 'knitwear'},
    {'name': 'Tops', 'slug': 'tops'},
    {'name': 'Bottoms', 'slug': 'bottoms'},
    {'name': 'Dresses', 'slug': 'dresses'},
    {'name': 'Jumpsuits', 'slug': 'jumpsuits'},
    {'name': 'Loungewear', 'slug': 'loungewear'},
]

PRODUCTS_DATA = [
    # ── WOMAN · Outerwear ──────────────────────────────────────────────────────
    {
        'name': 'MAVIS OVERSIZED TRENCH',
        'slug': 'mavis-oversized-trench',
        'category_slug': 'outerwear',
        'description': 'Classic oversized trench coat with a modern twist. Crafted from a premium cotton-blend fabric with a water-resistant finish.',
        'price': '345.00',
        'sizes': ['S', 'M', 'L'],
        'colors': ['Grey'],
        'stock': 15,
        'is_new': False,
        'gender': 'woman',
    },
    {
        'name': 'NAICA LEATHER JACKET',
        'slug': 'naica-leather-jacket',
        'category_slug': 'outerwear',
        'description': 'Premium leather jacket with a sleek silhouette. Features a zip-front closure and two side pockets.',
        'price': '285.00',
        'sizes': ['XS', 'S', 'M'],
        'colors': ['Black', 'Brown'],
        'stock': 8,
        'is_new': True,
        'gender': 'woman',
    },
    {
        'name': 'ARLISE TRENCH COAT',
        'slug': 'arlise-trench-coat',
        'category_slug': 'outerwear',
        'description': 'A sleek trench coat with a belted waist and double-breasted front. A timeless wardrobe staple.',
        'price': '325.00',
        'sizes': ['S', 'M'],
        'colors': ['Beige'],
        'stock': 10,
        'is_new': False,
        'gender': 'woman',
    },
    {
        'name': 'PEORIA SUEDE BLAZER',
        'slug': 'peoria-suede-blazer',
        'category_slug': 'outerwear',
        'description': 'A beautifully structured blazer crafted from supple suede with deep pockets and a relaxed silhouette.',
        'price': '278.00',
        'sizes': ['XS', 'S', 'M'],
        'colors': ['Tan', 'Black'],
        'stock': 7,
        'is_new': False,
        'gender': 'woman',
    },
    {
        'name': 'IVA BLAZER',
        'slug': 'iva-blazer',
        'category_slug': 'outerwear',
        'description': 'Sharp tailored blazer with a dramatic collar layered effect. A statement piece for any occasion.',
        'price': '489.00',
        'sizes': ['XS', 'S', 'M'],
        'colors': ['Black'],
        'stock': 6,
        'is_new': False,
        'gender': 'woman',
    },
    {
        'name': 'SHAY TRENCH COAT',
        'slug': 'shay-trench-coat',
        'category_slug': 'outerwear',
        'description': 'A floor-sweeping modern take on the dark trench coat. Dramatic and refined.',
        'price': '349.00',
        'sizes': ['S', 'M', 'L'],
        'colors': ['Navy'],
        'stock': 8,
        'is_new': True,
        'gender': 'woman',
    },
    {
        'name': 'LENA WOOL COAT',
        'slug': 'lena-wool-coat',
        'category_slug': 'outerwear',
        'description': 'Elegant double-breasted wool coat with a cinched waist and wide lapels. A winter essential.',
        'price': '420.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Camel', 'Black'],
        'stock': 12,
        'is_new': True,
        'gender': 'woman',
    },
    {
        'name': 'MIRA PUFFER JACKET',
        'slug': 'mira-puffer-jacket',
        'category_slug': 'outerwear',
        'description': 'Cropped puffer jacket with a high collar and quilted finish. Lightweight yet incredibly warm.',
        'price': '265.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Black', 'Cream', 'Pink'],
        'stock': 18,
        'is_new': False,
        'gender': 'woman',
    },

    # ── WOMAN · Knitwear ───────────────────────────────────────────────────────
    {
        'name': 'RAFAELA KNIT SWEATER',
        'slug': 'rafaela-knit-sweater',
        'category_slug': 'knitwear',
        'description': 'Soft and luxurious blend of cashmere and wool in a modern asymmetric cut. A wardrobe essential.',
        'price': '277.00',
        'sizes': ['S', 'M'],
        'colors': ['Charcoal', 'Cream'],
        'stock': 11,
        'is_new': False,
        'gender': 'woman',
    },
    {
        'name': 'CROPPED CREWNECK',
        'slug': 'cropped-crewneck-grey',
        'category_slug': 'knitwear',
        'description': 'Cropped crewneck sweater in a soft knit fabric. A minimalist essential with a relaxed, boxy silhouette.',
        'price': '650.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Grey', 'Yellow'],
        'stock': 14,
        'is_new': True,
        'gender': 'woman',
    },
    {
        'name': 'TANK TOP KNIT',
        'slug': 'tank-top-knit',
        'category_slug': 'knitwear',
        'description': 'Ribbed knit tank top with a sleek racerback silhouette. Versatile and form-fitting.',
        'price': '450.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Grey', 'Pink'],
        'stock': 18,
        'is_new': True,
        'gender': 'woman',
    },
    {
        'name': 'SWEATER',
        'slug': 'oversized-sweater-pink',
        'category_slug': 'knitwear',
        'description': 'Oversized drop-shoulder sweater in a soft mohair-blend knit. Effortlessly cozy and luxurious.',
        'price': '750.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Pink'],
        'stock': 12,
        'is_new': False,
        'gender': 'woman',
    },
    {
        'name': 'LOGO TANK TOP',
        'slug': 'logo-tank-top-white',
        'category_slug': 'knitwear',
        'description': 'Ribbed knit tank top with tonal logo embroidery at the chest. A sleek and sporty essential.',
        'price': '550.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['White'],
        'stock': 20,
        'is_new': False,
        'gender': 'woman',
    },
    {
        'name': 'CREWNECK SWEATER',
        'slug': 'crewneck-sweater-cream',
        'category_slug': 'knitwear',
        'description': 'Fitted crewneck sweater in a textured knit with subtle tonal stitching. A clean and versatile wardrobe essential.',
        'price': '720.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Cream'],
        'stock': 13,
        'is_new': False,
        'gender': 'woman',
    },
    {
        'name': 'BB LOGO CROPPED CREWNECK',
        'slug': 'bb-logo-cropped-crewneck',
        'category_slug': 'knitwear',
        'description': 'Cropped crewneck sweater with a bold BB Balenciaga logo embroidered at the chest. A signature statement piece.',
        'price': '850.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Black'],
        'stock': 10,
        'is_new': False,
        'gender': 'woman',
    },
    {
        'name': 'BB LOGO CROPPED HIGHNECK',
        'slug': 'bb-logo-cropped-highneck',
        'category_slug': 'knitwear',
        'description': 'Cropped highneck sweater with BB Balenciaga logo embroidery. Features a textured knit body and a sleek turtleneck collar.',
        'price': '920.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Black'],
        'stock': 9,
        'is_new': True,
        'gender': 'woman',
    },
    {
        'name': 'ARIA MOHAIR CARDIGAN',
        'slug': 'aria-mohair-cardigan',
        'category_slug': 'knitwear',
        'description': 'Oversized open-front cardigan in a fluffy mohair blend. Draped silhouette with deep pockets.',
        'price': '480.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Cream', 'Grey', 'Pink'],
        'stock': 14,
        'is_new': True,
        'gender': 'woman',
    },
    {
        'name': 'NOVA RIBBED TURTLENECK',
        'slug': 'nova-ribbed-turtleneck',
        'category_slug': 'knitwear',
        'description': 'Slim-fit ribbed turtleneck in a fine merino wool blend. A sleek and sophisticated layering piece.',
        'price': '390.00',
        'sizes': ['XS', 'S', 'M'],
        'colors': ['Black', 'Cream', 'Charcoal'],
        'stock': 16,
        'is_new': False,
        'gender': 'woman',
    },

    # ── WOMAN · Tops ───────────────────────────────────────────────────────────
    {
        'name': 'PRILLY OVERSIZED SHIRT',
        'slug': 'prilly-oversized-shirt',
        'category_slug': 'tops',
        'description': 'Oversized shirt in olive. A relaxed fit with a dropped shoulder and a curved hem.',
        'price': '169.00',
        'sizes': ['S', 'M', 'L'],
        'colors': ['Olive'],
        'stock': 20,
        'is_new': False,
        'gender': 'woman',
    },
    {
        'name': 'BEAUFILLE BAES CROP TOP',
        'slug': 'beaufille-baes-crop-top',
        'category_slug': 'tops',
        'description': 'Statement crop top crafted from high-gloss stretch vinyl. A bold and dramatic piece.',
        'price': '470.00',
        'sizes': ['XS', 'S', 'M'],
        'colors': ['Black'],
        'stock': 5,
        'is_new': False,
        'gender': 'woman',
    },
    {
        'name': 'SILK CAMI TOP',
        'slug': 'silk-cami-top',
        'category_slug': 'tops',
        'description': 'Delicate silk camisole with adjustable straps and a lace-trimmed neckline. Effortlessly elegant.',
        'price': '195.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Cream', 'Black', 'Pink'],
        'stock': 22,
        'is_new': True,
        'gender': 'woman',
    },
    {
        'name': 'LACE CORSET TOP',
        'slug': 'lace-corset-top',
        'category_slug': 'tops',
        'description': 'Structured corset top with intricate lace detailing and boning. A statement piece for evening wear.',
        'price': '285.00',
        'sizes': ['XS', 'S', 'M'],
        'colors': ['Black', 'White'],
        'stock': 8,
        'is_new': True,
        'gender': 'woman',
    },
    {
        'name': 'WRAP BLOUSE',
        'slug': 'wrap-blouse-woman',
        'category_slug': 'tops',
        'description': 'Fluid wrap blouse in a lightweight crepe fabric. Flattering V-neckline with a self-tie waist.',
        'price': '145.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Beige', 'Navy', 'Black'],
        'stock': 25,
        'is_new': False,
        'gender': 'woman',
    },

    # ── WOMAN · Bottoms ────────────────────────────────────────────────────────
    {
        'name': 'WIDE LEG TROUSERS',
        'slug': 'wide-leg-trousers-woman',
        'category_slug': 'bottoms',
        'description': 'High-waisted wide-leg trousers in a fluid crepe fabric. Elegant and effortlessly chic.',
        'price': '220.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Black', 'Beige', 'Navy'],
        'stock': 18,
        'is_new': False,
        'gender': 'woman',
    },
    {
        'name': 'MINI SKIRT',
        'slug': 'mini-skirt-black',
        'category_slug': 'bottoms',
        'description': 'Sleek mini skirt in a stretch fabric with a high waist and a fitted silhouette.',
        'price': '175.00',
        'sizes': ['XS', 'S', 'M'],
        'colors': ['Black', 'Grey'],
        'stock': 15,
        'is_new': True,
        'gender': 'woman',
    },
    {
        'name': 'MIDI SLIT SKIRT',
        'slug': 'midi-slit-skirt',
        'category_slug': 'bottoms',
        'description': 'Elegant midi skirt with a front slit and a fluid drape. Perfect for day-to-night dressing.',
        'price': '195.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Black', 'Cream', 'Olive'],
        'stock': 12,
        'is_new': False,
        'gender': 'woman',
    },
    {
        'name': 'TAILORED SHORTS',
        'slug': 'tailored-shorts-woman',
        'category_slug': 'bottoms',
        'description': 'High-waisted tailored shorts with a clean, structured silhouette. A versatile wardrobe staple.',
        'price': '155.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Black', 'Beige'],
        'stock': 20,
        'is_new': False,
        'gender': 'woman',
    },

    # ── WOMAN · Dresses ────────────────────────────────────────────────────────
    {
        'name': 'SLIP DRESS',
        'slug': 'slip-dress-satin',
        'category_slug': 'dresses',
        'description': 'Minimalist satin slip dress with thin straps and a bias-cut silhouette. Timeless and sensual.',
        'price': '310.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Black', 'Cream', 'Pink'],
        'stock': 14,
        'is_new': True,
        'gender': 'woman',
    },
    {
        'name': 'KNIT MIDI DRESS',
        'slug': 'knit-midi-dress',
        'category_slug': 'dresses',
        'description': 'Fitted ribbed knit midi dress with long sleeves and a mock neck. Sleek and sophisticated.',
        'price': '380.00',
        'sizes': ['XS', 'S', 'M'],
        'colors': ['Black', 'Charcoal', 'Cream'],
        'stock': 10,
        'is_new': False,
        'gender': 'woman',
    },
    {
        'name': 'WRAP MIDI DRESS',
        'slug': 'wrap-midi-dress',
        'category_slug': 'dresses',
        'description': 'Elegant wrap dress in a fluid crepe fabric with a V-neckline and a self-tie waist.',
        'price': '265.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Navy', 'Black', 'Olive'],
        'stock': 16,
        'is_new': False,
        'gender': 'woman',
    },
    {
        'name': 'MAXI EVENING DRESS',
        'slug': 'maxi-evening-dress',
        'category_slug': 'dresses',
        'description': 'Floor-length evening gown with a plunging neckline and a dramatic train. For the most special occasions.',
        'price': '890.00',
        'sizes': ['XS', 'S', 'M'],
        'colors': ['Black'],
        'stock': 5,
        'is_new': True,
        'gender': 'woman',
    },

    # ── WOMAN · Jumpsuits ──────────────────────────────────────────────────────
    {
        'name': 'TAILORED JUMPSUIT',
        'slug': 'tailored-jumpsuit-woman',
        'category_slug': 'jumpsuits',
        'description': 'Sleek tailored jumpsuit with wide-leg trousers and a belted waist. Effortlessly polished.',
        'price': '340.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Black', 'Navy'],
        'stock': 11,
        'is_new': False,
        'gender': 'woman',
    },
    {
        'name': 'LINEN JUMPSUIT',
        'slug': 'linen-jumpsuit-woman',
        'category_slug': 'jumpsuits',
        'description': 'Relaxed linen jumpsuit with a V-neckline and wide-leg silhouette. Perfect for warm weather.',
        'price': '245.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Beige', 'White', 'Olive'],
        'stock': 14,
        'is_new': True,
        'gender': 'woman',
    },

    # ── WOMAN · Loungewear ─────────────────────────────────────────────────────
    {
        'name': 'CASHMERE LOUNGE SET',
        'slug': 'cashmere-lounge-set-woman',
        'category_slug': 'loungewear',
        'description': 'Luxurious cashmere lounge set with a relaxed top and matching wide-leg pants. Ultimate comfort.',
        'price': '520.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Cream', 'Grey', 'Pink'],
        'stock': 9,
        'is_new': True,
        'gender': 'woman',
    },
    {
        'name': 'VELVET ROBE',
        'slug': 'velvet-robe-woman',
        'category_slug': 'loungewear',
        'description': 'Plush velvet robe with a shawl collar and deep pockets. Indulgent and cozy.',
        'price': '195.00',
        'sizes': ['S', 'M', 'L'],
        'colors': ['Black', 'Burgundy', 'Cream'],
        'stock': 13,
        'is_new': False,
        'gender': 'woman',
    },

    # ── MAN · Outerwear ────────────────────────────────────────────────────────
    {
        'name': 'ARBOR LEATHER JACKET',
        'slug': 'arbor-leather-jacket',
        'category_slug': 'outerwear',
        'description': 'Premium leather jacket with Arbor design. A bold statement piece for the modern wardrobe.',
        'price': '275.00',
        'sizes': ['S', 'M', 'L'],
        'colors': ['Black'],
        'stock': 12,
        'is_new': False,
        'gender': 'man',
    },
    {
        'name': 'PELSO BARN JACKET',
        'slug': 'pelso-barn-jacket',
        'category_slug': 'outerwear',
        'description': 'Classic oversized barn jacket with a corduroy collar and patched pockets. A rugged yet refined piece.',
        'price': '295.00',
        'sizes': ['S', 'M', 'L'],
        'colors': ['Navy', 'Olive'],
        'stock': 9,
        'is_new': True,
        'gender': 'man',
    },
    {
        'name': 'REX BOMBER JACKET',
        'slug': 'rex-bomber-jacket',
        'category_slug': 'outerwear',
        'description': 'Classic bomber jacket in a premium nylon shell with ribbed cuffs and hem. A timeless streetwear staple.',
        'price': '310.00',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Black', 'Olive', 'Navy'],
        'stock': 15,
        'is_new': False,
        'gender': 'man',
    },
    {
        'name': 'COLE OVERCOAT',
        'slug': 'cole-overcoat',
        'category_slug': 'outerwear',
        'description': 'Long structured overcoat in a premium wool blend. Clean lines and a relaxed fit for a modern silhouette.',
        'price': '495.00',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Charcoal', 'Camel', 'Black'],
        'stock': 8,
        'is_new': True,
        'gender': 'man',
    },
    {
        'name': 'DENIM TRUCKER JACKET',
        'slug': 'denim-trucker-jacket',
        'category_slug': 'outerwear',
        'description': 'Classic denim trucker jacket with a slightly oversized fit and contrast stitching.',
        'price': '185.00',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Blue', 'Black'],
        'stock': 20,
        'is_new': False,
        'gender': 'man',
    },
    {
        'name': 'FIELD JACKET',
        'slug': 'field-jacket-man',
        'category_slug': 'outerwear',
        'description': 'Military-inspired field jacket with multiple pockets and a relaxed fit. Functional and stylish.',
        'price': '255.00',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Olive', 'Tan', 'Black'],
        'stock': 14,
        'is_new': False,
        'gender': 'man',
    },

    # ── MAN · Knitwear ─────────────────────────────────────────────────────────
    {
        'name': 'JW ANDERSON JUMPER',
        'slug': 'jw-anderson-jumper',
        'category_slug': 'knitwear',
        'description': 'Distinctive tie-waist detail on a relaxed fit crewneck jumper. A signature piece from the collection.',
        'price': '790.00',
        'sizes': ['M', 'L'],
        'colors': ['Olive'],
        'stock': 4,
        'is_new': False,
        'gender': 'man',
    },
    {
        'name': 'BOATNECK SWEATER',
        'slug': 'boatneck-sweater',
        'category_slug': 'knitwear',
        'description': 'Classic boatneck sweater with navy stripe detail and embroidered logo at the hem.',
        'price': '890.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Cream', 'Navy'],
        'stock': 9,
        'is_new': False,
        'gender': 'man',
    },
    {
        'name': 'HYBRID JUMPER',
        'slug': 'hybrid-jumper',
        'category_slug': 'knitwear',
        'description': 'Cropped hybrid jumper combining a striped knit top with a layered shirt collar. A bold, deconstructed statement piece.',
        'price': '1150.00',
        'sizes': ['XS', 'S', 'M'],
        'colors': ['Cream', 'Navy'],
        'stock': 6,
        'is_new': True,
        'gender': 'man',
    },
    {
        'name': 'ZIP-UP SWEATER',
        'slug': 'zip-up-sweater-black',
        'category_slug': 'knitwear',
        'description': 'Slim-fit zip-up sweater in a fine-gauge knit with a high collar. A refined and modern layering piece.',
        'price': '980.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Black'],
        'stock': 8,
        'is_new': True,
        'gender': 'man',
    },
    {
        'name': 'BACK-TO-FRONT HIGH NECK SWEATER',
        'slug': 'back-to-front-high-neck-sweater',
        'category_slug': 'knitwear',
        'description': 'Oversized high neck sweater with a signature back-to-front construction. Worn with the seams facing outward for a deconstructed aesthetic.',
        'price': '1250.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Cream', 'Charcoal'],
        'stock': 7,
        'is_new': True,
        'gender': 'man',
    },
    {
        'name': 'V-NECK SWEATER',
        'slug': 'v-neck-sweater-grey',
        'category_slug': 'knitwear',
        'description': 'Relaxed V-neck sweater in a soft cashmere-blend knit. A timeless and effortless layering piece.',
        'price': '680.00',
        'sizes': ['XS', 'S', 'M', 'L'],
        'colors': ['Grey'],
        'stock': 15,
        'is_new': False,
        'gender': 'man',
    },
    {
        'name': 'CABLE KNIT SWEATER',
        'slug': 'cable-knit-sweater-man',
        'category_slug': 'knitwear',
        'description': 'Classic cable knit sweater in a chunky wool blend. Relaxed fit with a crew neck and ribbed cuffs.',
        'price': '340.00',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Cream', 'Grey', 'Navy'],
        'stock': 18,
        'is_new': False,
        'gender': 'man',
    },
    {
        'name': 'HALF-ZIP PULLOVER',
        'slug': 'half-zip-pullover-man',
        'category_slug': 'knitwear',
        'description': 'Sporty half-zip pullover in a fine merino wool blend. Clean and minimal with a modern athletic feel.',
        'price': '295.00',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Black', 'Navy', 'Charcoal'],
        'stock': 20,
        'is_new': True,
        'gender': 'man',
    },

    # ── MAN · Tops ─────────────────────────────────────────────────────────────
    {
        'name': 'ROTATE OVERSIZED T-SHIRT',
        'slug': 'rotate-oversized-t-shirt',
        'category_slug': 'tops',
        'description': 'A clean, modern oversized tee. Made from 100% organic cotton with a relaxed fit.',
        'price': '90.00',
        'sizes': ['S', 'M', 'L'],
        'colors': ['White', 'Black'],
        'stock': 30,
        'is_new': False,
        'gender': 'man',
    },
    {
        'name': 'OXFORD BUTTON-DOWN',
        'slug': 'oxford-button-down-man',
        'category_slug': 'tops',
        'description': 'Classic Oxford button-down shirt in a premium cotton fabric. A wardrobe essential for any occasion.',
        'price': '145.00',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['White', 'Blue', 'Black'],
        'stock': 25,
        'is_new': False,
        'gender': 'man',
    },
    {
        'name': 'LINEN SHIRT',
        'slug': 'linen-shirt-man',
        'category_slug': 'tops',
        'description': 'Relaxed linen shirt with a camp collar and a slightly oversized fit. Perfect for warm weather.',
        'price': '135.00',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['White', 'Beige', 'Olive'],
        'stock': 22,
        'is_new': True,
        'gender': 'man',
    },
    {
        'name': 'GRAPHIC TEE',
        'slug': 'graphic-tee-man',
        'category_slug': 'tops',
        'description': 'Premium cotton graphic tee with an oversized fit and a bold front print. A streetwear essential.',
        'price': '95.00',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Black', 'White', 'Grey'],
        'stock': 35,
        'is_new': False,
        'gender': 'man',
    },
    {
        'name': 'POLO SHIRT',
        'slug': 'polo-shirt-man',
        'category_slug': 'tops',
        'description': 'Classic piqué polo shirt with a slim fit and a ribbed collar. A refined casual essential.',
        'price': '120.00',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['White', 'Navy', 'Black'],
        'stock': 28,
        'is_new': False,
        'gender': 'man',
    },

    # ── MAN · Bottoms ──────────────────────────────────────────────────────────
    {
        'name': 'SLIM CHINOS',
        'slug': 'slim-chinos-man',
        'category_slug': 'bottoms',
        'description': 'Slim-fit chino trousers in a stretch cotton fabric. Clean and versatile for any occasion.',
        'price': '165.00',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Beige', 'Navy', 'Black', 'Olive'],
        'stock': 24,
        'is_new': False,
        'gender': 'man',
    },
    {
        'name': 'WIDE LEG TROUSERS',
        'slug': 'wide-leg-trousers-man',
        'category_slug': 'bottoms',
        'description': 'Relaxed wide-leg trousers in a premium wool blend. A modern take on classic tailoring.',
        'price': '245.00',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Charcoal', 'Black', 'Beige'],
        'stock': 16,
        'is_new': True,
        'gender': 'man',
    },
    {
        'name': 'CARGO PANTS',
        'slug': 'cargo-pants-man',
        'category_slug': 'bottoms',
        'description': 'Relaxed cargo pants with multiple utility pockets and a tapered leg. Functional and stylish.',
        'price': '195.00',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Olive', 'Black', 'Tan'],
        'stock': 20,
        'is_new': False,
        'gender': 'man',
    },
    {
        'name': 'TAILORED SHORTS',
        'slug': 'tailored-shorts-man',
        'category_slug': 'bottoms',
        'description': 'Structured tailored shorts in a premium cotton blend. Clean lines and a relaxed fit.',
        'price': '145.00',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Black', 'Navy', 'Beige'],
        'stock': 18,
        'is_new': False,
        'gender': 'man',
    },

    # ── MAN · Loungewear ───────────────────────────────────────────────────────
    {
        'name': 'TERRY TRACKSUIT',
        'slug': 'terry-tracksuit-man',
        'category_slug': 'loungewear',
        'description': 'Matching terry cloth tracksuit with a zip-up hoodie and straight-leg pants. Retro-inspired comfort.',
        'price': '285.00',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Grey', 'Navy', 'Black'],
        'stock': 14,
        'is_new': True,
        'gender': 'man',
    },
    {
        'name': 'FLEECE HOODIE',
        'slug': 'fleece-hoodie-man',
        'category_slug': 'loungewear',
        'description': 'Oversized fleece hoodie with a kangaroo pocket and a relaxed fit. Ultimate cozy comfort.',
        'price': '175.00',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Grey', 'Black', 'Cream'],
        'stock': 25,
        'is_new': False,
        'gender': 'man',
    },
    {
        'name': 'SWEATPANTS',
        'slug': 'sweatpants-man',
        'category_slug': 'loungewear',
        'description': 'Premium cotton sweatpants with a tapered leg and an elasticated waistband. Comfortable and stylish.',
        'price': '135.00',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Grey', 'Black', 'Navy'],
        'stock': 30,
        'is_new': False,
        'gender': 'man',
    },

    # ── MAN · Jumpsuits ────────────────────────────────────────────────────────
    {
        'name': 'UTILITY JUMPSUIT',
        'slug': 'utility-jumpsuit-man',
        'category_slug': 'jumpsuits',
        'description': 'Relaxed utility jumpsuit with multiple pockets and a belted waist. A modern workwear-inspired piece.',
        'price': '295.00',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Olive', 'Black', 'Tan'],
        'stock': 10,
        'is_new': True,
        'gender': 'man',
    },
]


class Command(BaseCommand):
    help = 'Seed the database with sample products and categories'

    def handle(self, *args, **options):
        self.stdout.write('Seeding categories...')
        categories = {}
        for cat_data in CATEGORIES_DATA:
            cat, created = Category.objects.get_or_create(
                slug=cat_data['slug'],
                defaults={'name': cat_data['name']},
            )
            categories[cat_data['slug']] = cat
            if created:
                self.stdout.write(f'  Created category: {cat.name}')

        self.stdout.write('Seeding products...')
        for prod_data in PRODUCTS_DATA:
            category = categories.get(prod_data['category_slug'])
            product, created = Product.objects.get_or_create(
                slug=prod_data['slug'],
                defaults={
                    'name': prod_data['name'],
                    'category': category,
                    'description': prod_data['description'],
                    'price': prod_data['price'],
                    'sizes': prod_data['sizes'],
                    'colors': prod_data['colors'],
                    'stock': prod_data['stock'],
                    'is_new': prod_data['is_new'],
                    'gender': prod_data.get('gender', 'unisex'),
                    'is_active': True,
                },
            )
            if created:
                self.stdout.write(f'  Created product: {product.name}')
            else:
                # Update gender for existing products
                Product.objects.filter(slug=prod_data['slug']).update(
                    gender=prod_data.get('gender', 'unisex')
                )

        self.stdout.write(self.style.SUCCESS('Done! Database seeded successfully.'))
        self.stdout.write(self.style.WARNING(
            'Note: Product images must be uploaded manually via Django Admin or by placing files in /media/products/'
        ))
