# Generated by Django 5.0.6 on 2026-06-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('woman', 'Woman'), ('man', 'Man'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
    ]
