# Generated by Django 5.0.6 on 2026-06-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unavailable_sizes',
            field=models.JSONField(blank=True, default=list, help_text='Sizes that are sold out (will be shown crossed out)'),
        ),
    ]
